### ISSUE TITLE
implement wasm Gamepad

### ISSUE THREAD

**Issue by nkast** [kniEngine/kni#1620]
- [x] Implement wasm Gamepad object and Navigator.GetGamepads() method.
- [x] Implement wasm GamepadEvent, Window.GamepadConnected & Window.GamepadDisconnected events.

https://github.com/nkast/Wasm

https://developer.mozilla.org/en-US/docs/Web/API/Touch_events

- [x] [BlazorGL] Implement Gamepad.

https://github.com/kniEngine/kni/blob/main/MonoGame.Framework/Input/.Blazor/ConcreteGamePad.cs

**Comment by vchelaru** [comment]
+1 to this, I'm looking forward to bringing some of my games to itch.io web but they all use gamepad.

**Comment by nkast** [comment]
Gamepad API
b8a2ddcf59c4a2740c9b41946369ae136f5ae6f5

**Comment by nkast** [comment]
closed by #1730
