### ISSUE TITLE
Android crash when sound is Up or Down from physical buttons

### ISSUE THREAD

**Issue by gaetandezeiraud** [kniEngine/kni#1635]
The Android project template crash at startup if the volume up or down is pressed at startup (just after the splash screen) with a `System.NullReferenceException: 'Object reference not set to an instance of an object.'`. 

One temporary workaround I found is to create a custom FrameLayout with a `public override bool DispatchKeyEvent(KeyEvent e)` and ignore when `if (e.Action == KeyEventActions.Down || e.Action == KeyEventActions.Up)`. Not really a fix.

![image](https://github.com/kniEngine/kni/assets/1573282/07381ef7-2fd4-4066-81d0-4e809024bd6e)

The problem is reproducible each time. On Android 9 and also 13 so I think all versions.

#### What version of KNI does the bug occur on:
- KNI 3.12.9001

#### What KNI platform are you using:
- Android

**Comment by gaetandezeiraud** [comment]
I saw this commit recently https://github.com/kniEngine/kni/commit/86aaa3cd4360c81636bc8e6026f68d2bc0e562fe.
Does it mean no fix for this issue? Because it is maybe related to Xamarin?

**Comment by nkast** [comment]
The error was introduces in https://github.com/kniEngine/kni/pull/1378

**Comment by nkast** [comment]
Thanks for reporting, @gaetandezeiraud.
