### ISSUE TITLE
Cannot Create Multiplatform Template in VS 2022 17.10.2

### ISSUE THREAD

**Issue by thygrrr** [kniEngine/kni#1672]
Trying to create the multiplatform template results in an empty / configuration-less project.
During the creation process, Visual Studio gives me a series of errors. 

I attached the generated project files for reference.
[repro-project-as-generated.zip](https://github.com/user-attachments/files/15837475/repro-project-as-generated.zip)

![image](https://github.com/kniEngine/kni/assets/8904620/d8cdb005-e1e7-4669-9439-042602018c8c)

This is my general dev system and I just installed basically all workloads to make sure it's not something missing on my end. (maybe it still is, but at this point I'm stumped)

![devenv_DUMyd49fMf](https://github.com/kniEngine/kni/assets/8904620/02693205-12f6-45b4-a259-b9ed3f9e0b96)
![devenv_tZnu4Qi4Dc](https://github.com/kniEngine/kni/assets/8904620/762c8351-e90f-440f-991a-3c72cdc99e83)
![devenv_tcyn6QyTCK](https://github.com/kniEngine/kni/assets/8904620/731ca1b3-7743-4210-a729-41c8770a6100)
![devenv_65QXtFrO7V](https://github.com/kniEngine/kni/assets/8904620/522a4e31-983f-437c-9941-ebc332190b3a)
![devenv_wpxpkR4iDd](https://github.com/kniEngine/kni/assets/8904620/11120c90-2a90-417e-9dc4-c349c1d6da01)

It has literally no configurations and only the shared project (not sure what's expected, but I would have assumed some additional .csproj files). The mentioned path in the error messages apparently exists (see attached zip and following screenshots)

There's no suitable project to set as startup...
![image](https://github.com/kniEngine/kni/assets/8904620/fa9a70b1-df54-4ef8-9b94-f60f7381b8de)
![image](https://github.com/kniEngine/kni/assets/8904620/1c3d920e-39d1-4c94-b565-ece82264d1da)

... and Rider finds it equally barren.
![image](https://github.com/kniEngine/kni/assets/8904620/8842a6ca-c849-4678-b9f7-6eeadeb9e296)
![image](https://github.com/kniEngine/kni/assets/8904620/04952635-6982-4dfc-8932-dc17368e69c5)

#### What version of KNI does the bug occur on:
- KNI 3.12.9001

#### What operating system are you using:
- Windows 11 Pro 23H2 22631.3527 
- Dev Drive mounted as P:\ (selected for project destination) and also as NTFS Path C:\Projects
- Visual Studio Communty 2022 17.10.2 (previous version also affected)
- Locales en_DE ("English (Germany)"), but for shells, it's Get-WinSystemLocale: 2057 en-GB English (United Kingdom)

```pwsh
PS P:\> dotnet --list-sdks
6.0.129 [C:\Program Files\dotnet\sdk]
6.0.203 [C:\Program Files\dotnet\sdk]
6.0.321 [C:\Program Files\dotnet\sdk]
6.0.421 [C:\Program Files\dotnet\sdk]
7.0.408 [C:\Program Files\dotnet\sdk]
8.0.104 [C:\Program Files\dotnet\sdk]
8.0.204 [C:\Program Files\dotnet\sdk]
8.0.300 [C:\Program Files\dotnet\sdk]
```

#### What KNI platform are you using:

- Multiplatform Template

**Comment by thygrrr** [comment]
The same error exists trying to generate on a different volume e.g.
![image](https://github.com/kniEngine/kni/assets/8904620/09ec5141-fe67-401f-a085-3e68b7490b4f)

**Comment by nkast** [comment]
The problem is that the templates use $safeprojectname$ in some places and $projectname$ in other...

As for the problems with dots in the project name, it looks like using custom class names isn't really supported, and we have to revert back to a fixed name, like `Game1`.
I am going to ignore this problem, and revisit it once we move to new dotNet templates. https://github.com/kniEngine/kni/issues/1617
