### ISSUE TITLE
AlphaTestEffect problem

### ISSUE THREAD

**Issue by jordi-z80** [kniEngine/kni#1717]
- KNI 3.12.9001 (nuget)
- Windows10
- WindowsDX

I'm having a problem with AlphaTestEffect, it's like the effect can't read the AlphaTestParam. The following sample crashes.

<code>

		AlphaTestEffect effect;
		Texture2D tex;

		void onLoad ()
		{
			effect = new AlphaTestEffect (GraphicsDevice);
			tex = new Texture2D (GraphicsDevice, 1, 1);
			tex.SetData (new Color[] { Color.White });
		}

		void onDraw ()
		{
			spriteBatch.Begin (effect: effect);
			spriteBatch.Draw (tex, new Rectangle (100, 100, 200, 200), Color.Red);
			spriteBatch.End ();
		}
<code>

I've been a long time away of Xna/MG so I don't know if I'm doing something wrong :)

**Comment by nkast** [comment]
What do you mean crashes? 
What's the error message?

**Comment by jordi-z80** [comment]
Sorry, I knew I was forgetting something :)

System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Xna.Framework.Graphics
  StackTrace:
   at Microsoft.Xna.Framework.Graphics.AlphaTestEffect.OnApply()


for some reason, the full stack trace is not in the exception...

![image](https://github.com/user-attachments/assets/f9cd6f33-85b9-41cb-a063-43c717398ffe)

**Comment by nkast** [comment]
Confirmed.

https://github.com/kniEngine/kni/blob/7e1ba169d1f5d0f4c66246543657495bc25f7efc/src/Xna.Framework.Graphics/Graphics/GraphicsDeviceStrategy.cs#L244

Thanks for reporting @jordi-z80
