### ISSUE TITLE
Building .fx file results in HRESULT: [0x8876086C]

### ISSUE THREAD

**Issue by vchelaru** [kniEngine/kni#1718]
Attempting to build the .fx file included in this issue causes the following error:

![image](https://github.com/user-attachments/assets/e2cd6514-4ce9-4d36-9708-b731166d1127)

I had to .zip the shader file because GitHub does not accept .fx extensions, but does accept .zip.
[Shader.zip](https://github.com/user-attachments/files/16202249/Shader.zip)

```
OS Name	Microsoft Windows 11 Pro
Version	10.0.22631 Build 22631
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	MSI
System Manufacturer	Micro-Star International Co., Ltd.
System Model	Raider GE76 12UE
System Type	x64-based PC
System SKU	17K4.2
Processor	12th Gen Intel(R) Core(TM) i7-12700H, 2700 Mhz, 14 Core(s), 20 Logical Processor(s)
BIOS Version/Date	American Megatrends International, LLC. E17K4IMS.20B, 3/27/2023
SMBIOS Version	3.4
Embedded Controller Version	255.255
BIOS Mode	UEFI
BaseBoard Manufacturer	Micro-Star International Co., Ltd.
BaseBoard Product	MS-17K4
BaseBoard Version	REV:1.0
Platform Role	Mobile
Secure Boot State	On
PCR7 Configuration	Elevation Required to View
Windows Directory	C:\Windows
System Directory	C:\Windows\system32
Boot Device	\Device\HarddiskVolume1
Locale	United States
Hardware Abstraction Layer	Version = "10.0.22621.2506"
User Name	MSI\Owner
Time Zone	Mountain Daylight Time
Installed Physical Memory (RAM)	64.0 GB
```

```
Name	NVIDIA GeForce RTX 3060 Laptop GPU
PNP Device ID	PCI\VEN_10DE&DEV_2520&SUBSYS_13241462&REV_A1\4&3062272C&0&0008
Adapter Type	NVIDIA GeForce RTX 3060 Laptop GPU, NVIDIA compatible
Adapter Description	NVIDIA GeForce RTX 3060 Laptop GPU
Adapter RAM	(1,048,576) bytes
Installed Drivers	C:\Windows\System32\DriverStore\FileRepository\nvmi.inf_amd64_a29eb0fbdc950996\nvldumdx.dll,C:\Windows\System32\DriverStore\FileRepository\nvmi.inf_amd64_a29eb0fbdc950996\nvldumdx.dll,C:\Windows\System32\DriverStore\FileRepository\nvmi.inf_amd64_a29eb0fbdc950996\nvldumdx.dll,C:\Windows\System32\DriverStore\FileRepository\nvmi.inf_amd64_a29eb0fbdc950996\nvldumdx.dll
Driver Version	31.0.15.2892
```

#### What version of KNI does the bug occur on:
- KNI 3.12.9001.0

#### What operating system are you using:
- Windows11

#### What KNI platform are you using:

- DesktopGL

**Comment by vchelaru** [comment]
As a workaround, vertex shader can be modified to vs_2_0 instead of vs_1_1

![image](https://github.com/user-attachments/assets/4092d2ed-e26e-435e-8963-348d477cebcb)

I've been asked to keep this issue open so that if the shader does use vs_1_1 a more informative error is presented to the user.

**Comment by nkast** [comment]
The fix is to use vs_2_0, ps_2_0, DX11 compiler can't compile sm1.1 shaders.
Next version will give a more informative error.

This is backwards compatible with XNA as well, since  Reach could support sm2.0 and HiDef was sm3.0.
