### ISSUE TITLE
[BlazorGL] Playing a SoundEffect which is loaded FromStream should not produce an exception

### ISSUE THREAD

**Issue by vchelaru** [kniEngine/kni#1739]
If a .wav file is loaded from stream then played, an exception is thrown. Instead, the sound should play normally.

The following code was used to reproduce the error:

```cs
using var stream = TitleContainer.OpenStream(assetName);
soundEffect = SoundEffect.FromStream(stream);

// later...

soundEffect.Play();
```

This produces the following exception in the browser debug console:

```
marshal-to-js.ts:349 Uncaught    at nkast.Wasm.Audio.AudioBufferSourceNode.set_Buffer(AudioBuffer value)
   at Microsoft.Xna.Platform.Audio.ConcreteSoundEffectInstance.PlatformPlay(Boolean isLooped)
   at Microsoft.Xna.Framework.Audio.SoundEffectInstance.Play()
   at Microsoft.Xna.Platform.Audio.AudioService.Play(SoundEffect effect)
   at Microsoft.Xna.Framework.Audio.SoundEffect.Play()
   ...
```

I have not tried this from XNB.

#### What version of KNI does the bug occur on:
- KNI 3.12.9001

#### What operating system are you using:
- Windows11

#### What KNI platform are you using:

- BlazorGL

**Comment by nkast** [comment]
relate report: https://github.com/kniEngine/kni/discussions/1716

**Comment by vchelaru** [comment]
Yes this seems related. I have also since tried loading from .XNB and as #1176 reports, I can successfully load from XNB.
