### ISSUE TITLE
TitleContainer will fail when reading text that has characters beyond ascii 255

### ISSUE THREAD

**Issue by vchelaru** [kniEngine/kni#1762]
The current implementation of TitleContainer for Blazor loops through a string response and only pulls the last 2 bytes from the character:

https://github.com/kniEngine/kni/blob/ffae6ab3ea93904c07b3ce4489b15e0dfa290ccb/Platforms/.Blazor/ConcreteTitleContainer.cs#L37

If loading a file which is text that contains strings that have characters that are larger than this value (such as "smart quotes"), these values get modified when the stream is returned. Furthermore, by looping through the text letter-by-letter, this can add additional performance costs to the process of loading content.

I attempted to look into how to fix this but it seems to dive into a class that I'm not familiar with. I'm also not sure if simply encoding the text as UTF-8 would solve the problem, so I'm not sure if that is the right solution.

#### What version of KNI does the bug occur on:
- KNI 3.13.9001

#### What operating system are you using:
- Windows11

#### What KNI platform are you using:

- BlazorGL

**Comment by vchelaru** [comment]
I've played around with this solution on my end and it seemed to work well, but I'd say I'm still in the process of testing it:

```
var buffer = System.Text.Encoding.UTF8.GetBytes(responseText);
```

**Comment by nkast** [comment]
reference: https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest_API/Sending_and_Receiving_Binary_Data#receiving_binary_data_in_older_browsers

**Comment by vchelaru** [comment]
I can no longer reproduce the problem, I dont' know what is going on, but I'll close it for now.
