### ISSUE TITLE
Insufficient documentation, can't figure out how to use it

### ISSUE THREAD

**Issue by KiwifruitDev** [kniEngine/kni#1784]
There doesn't seem to be any documentation for nuget or porting from MonoGame.

I have the following entries in my `csproj` file:

```xml
<ItemGroup>
  <TrimmerRootAssembly Include="Microsoft.Xna.Framework.Content.ContentTypeReader" Visible="false" />
</ItemGroup>
<ItemGroup>
  <PackageReference Include="MonoGame.Extended.Tweening" Version="3.8.0" />
  <PackageReference Include="MonoGame.Content.Builder.Task" Version="3.8.0.1641" />
  <PackageReference Include="MonoGame.Framework.WindowsDX" Version="3.8.1.303" />
  <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  <PackageReference Include="WindowsAPICodePack-Core" Version="1.1.2" />
  <PackageReference Include="WindowsAPICodePack-Shell" Version="1.1.1" />
  <PackageReference Include="SharpCompress" Version="0.37.2" />
</ItemGroup>
<ItemGroup>
  <MonoGameContentReference Include="Content\Content.mgcb" />
</ItemGroup>
```

I would like to port my project to KNI for web use, but there doesn't seem to be any nuget packages for KNI.

Are there any porting instructions? The `README.md` doesn't mention how to incorporate this into a project.

**Comment by nkast** [comment]
There is a description here https://github.com/kniEngine/kni/blob/main/Documentation/articles/migrate_381.md

**Comment by nkast** [comment]
For the BlazorGL you need to create a new project.
It's not possible to swap the dlls from a WindowsDX project, because it's for the most part an asp.net Webassembly project.
