### ISSUE TITLE
BlazorGL 'Shader Compilation Failed' runtime exception using fwidth function

### ISSUE THREAD

**Issue by dtaylorus** [kniEngine/kni#1816]
Shaders that use the `fwidth` function build successfully with the content pipeline but fail at runtime in KNI BlazorGL with the exception 'Shader Compilation Failed'.

My best guess is the following is required to be added to the BlazorGL shader as it is in DesktopGL:

```
#extension GL_OES_standard_derivatives : enable
```

Here's an example shader that works on MonoGame DesktopGL, iOS, and Android but fails on KNI BlazorGL due to the `fwidth` function call.

```
#if OPENGL
	#define SV_POSITION POSITION
	#define VS_SHADERMODEL vs_3_0
	#define PS_SHADERMODEL ps_3_0
#else
	#define VS_SHADERMODEL vs_4_0_level_9_3
	#define PS_SHADERMODEL ps_4_0_level_9_3
#endif

float2 TextureSize;
float PxRange;
float Thickness;

sampler SpriteTextureSampler : register(s0);

struct VertexShaderOutput
{
	float4 Position : SV_POSITION;
	float4 Color : COLOR0;
	float2 TexCoord : TEXCOORD0;
};

float Median(float a, float b, float c)
{	
	return max(min(a, b), min(max(a, b), c));
}

float LinearStep(float a, float b, float x) {
	return clamp((x - a) / (b - a), 0.0, 1.0);
}

float4 SamplePS(VertexShaderOutput input) : COLOR
{
	float2 p = input.TexCoord;
	float pxSize = min(0.5 / PxRange * (fwidth(p.x) * TextureSize.x + fwidth(p.y) * TextureSize.y), 0.25);

	float3 samp = tex2D(SpriteTextureSampler, p).rgb;

	float sigDist = 2.0f * Median(samp.r, samp.g, samp.b) - 1.0f + Thickness;

	float opacity = LinearStep(-pxSize, pxSize, sigDist);

	return input.Color * opacity;
}

technique SmoothText
{
	pass P0
	{
		PixelShader = compile PS_SHADERMODEL SamplePS();		
	}
};
```

#### What version of KNI does the bug occur on:
- KNI 3.13.9001

#### What operating system are you using:
- Windows11

#### What KNI platform are you using:

- BlazorGL

**Comment by dtaylorus** [comment]
`fwidth` gets translated into GLSL `dFdx` and `dFdy` which requires a newer version of GLES specified like this:

```
#version 300 es
```

It looks like Mojoshader does not generate valid GLES 3 shader code, so further fixup is required.

**Comment by dtaylorus** [comment]
So far I've managed to get a pixel shader to compile with `#version 300 es`, in combination with some hacks to fix up the GLSL code output by Mojoshader which are outlined nicely at https://webgl2fundamentals.org/webgl/lessons/webgl1-to-webgl2.html.

There's still a problem which I think is that the default vertex shader version doesn't match the new pixel shader version. I'm looking into that next.

So far I've tried using the following vertex shader, which I thought might match the default vertex shader, and in fact the runtime exception does go away. But there's something wrong with the vertex shader itself since nothing is output on the display.

```
struct VertexShaderOutput
{
	float4 Position : SV_Position;
	float4 Color : COLOR0;
	float2 TexCoord : TEXCOORD0;
};

VertexShaderOutput SampleVertexShader(VertexShaderInput v)
{
	VertexShaderOutput output;

	output.Position = v.Position;
	output.Color = v.Color;
	output.TexCoord = v.TexCoord;
	return output;
}
```

Next up I'm looking into how the default vertex shader is generated to see if I can fix that up at runtime instead of trying to supply a vertex shader.

**Comment by dtaylorus** [comment]
@nkast I realized I didn't answer your question. No, `#version 300 es` does not work on the Reach profile with WebGL 1. We get a runtime error that the shader could not be linked. That error goes away when using the HiDef profile with WebGL 2.

**Comment by dtaylorus** [comment]
Note: It looks like the default vertex shader comes from `SpriteEffect` which in turn comes from a resource named `Resources.SpriteEffect.fxo` which may need to be rebuilt with `#version 300 es` so it can be paired with a GLES 3 fragment shader.

**Comment by nkast** [comment]
That is expected. In Reach profile sm3.0 will not run, neither will fwidth.

Are there any issues in HiDef thou?

The vertex shader in SpriteEffext has to work with Reach profile (WebGL1),
so no such change can to be made there. The default vertex shader shouldn't have anything to do with the version of fragment shader since it's a very simple code.
You always could mix and match different shader versions of vs/ps in a shad.

**Comment by dtaylorus** [comment]
HiDef and WebGL2 seem to work fine for me. I just have to figure out how to use my GLES 3 pixel shader with the SpriteEffect vertex shader.

I'm currently going down the path of copying the SpriteEffect vertex shader into my shader and converting it to GLES 3 rather than changing the default SpriteEffect vertex shader as you say.

**Comment by nkast** [comment]
What changes are required ?

**Comment by dtaylorus** [comment]
No, I mean that if my pixel shader byte code has `#version 300 es` in it and I don't specify a vertex shader, then I get a runtime failure because the default vertex shader from SpriteEffect has a version mismatch (because it's still a GLSL 1 shader without the `#version 300 es`) and apparently you can't mix versions of pixel and vertex shaders.

If either the pixel or vertex shader has `#version 300 es`, they both have to have it.

So I have to replace the default vertex shader from SpriteEffect with my own vertex shader that has `#version 300 es` in it.

**Comment by nkast** [comment]
I still dont understand if there is an issue here. If you build your effects with vs and ps set to 3_0,
and set the graphics profile to HiDef in the graphicsDeviceManager,
are you getting any errors when using fwidth?

I mean with the stock builder without any further patching.

**Comment by dtaylorus** [comment]
Yes, I have some hacks in the `ShaderProfileGL.CreateGLSL` content builder method to transform the WebGL shader code to work with fwidth.

These are the only changes. I was able to workaround the rest of the issues in my game code.

Here they are:

```
            glslCode = glslCode.Replace("attribute ", "in ");

            if (shaderStage == ShaderStage.Pixel)
            {
                glslCode = glslCode.Replace("varying ", "in ");
            }
            else
            {
                glslCode = glslCode.Replace("varying ", "out ");
            }

            glslCode = glslCode.Replace("texture2D", "texture");

            glslCode = glslCode.Replace("#define ps_oC0 gl_FragColor", "out vec4 ps_oC0;");

            glslCode = "#version 300 es\r\n" + glslCode;
```

These work for me. I imagine it would be better to update to a newer build of Mojoshader and generate correct GLES3 shader code in the first place, but this is probably beyond the scope I can tackle.

Really happy to have my game fully rendering in the browser with smoothed MSDF fonts now.

**Comment by dtaylorus** [comment]
@nkast I submitted the changes as a pull request so you can see them. I imagine you can't accept them without scoping them to BlazorGL + HiDef somehow, but I wasn't sure how you'd like to do that.

**Comment by dtaylorus** [comment]
In my opinion, the best option going forward is to drop support for WebGL 1 and switch all the shaders to GLES 3.

**Comment by nkast** [comment]
I've setup a BlazorGL project for the [Animation sample](https://github.com/nkast/Aether.Extras/tree/main/Samples/Animation/Animation.BlazorGL).

I can confirm that the standard_derivatives functions require 300es shaders, 
and also that mixing Vertex/Fragment shaders of different versions isn't allowed.

The only option a see at the moment is to patch all shaders at runtime.

Possibly in the future we could include both versions in the .xnb when we update the effect format.

PR #1833 for review....

**Comment by dtaylorus** [comment]
Awesome. Thanks for the elegant fix to patch at runtime and fixup the default shaders like SpriteEffect. It should make it possible to simply switch the profile from Reach to HiDef with no code changes for the shader or effects.
