### ISSUE TITLE
Parameter names are not the same on desktop and web

### ISSUE THREAD

**Issue by vchelaru** [kniEngine/kni#1957]
I have not tested this with the latest Kni version because I've had some issues upgrading. If this issue is suspected to be only in older versions please let me know and I can focus more on upgrading soon.

Parameter names are not the same comparing MonoGame DesktopGL and Kni Web.

![image](https://github.com/user-attachments/assets/0a512698-2b42-429a-9c09-eb3fe6f1b635)

![image](https://github.com/user-attachments/assets/0ff5a0ea-9b1c-46bc-8ace-5212d42d074f)

Therefore, this code works on desktop but not on Kni web:

```cs
_bloomParameterScreenTexture = _bloomEffect.Parameters["LinearSampler+ScreenTexture"];
```
Instead, I have to unqualify the parameter:
```cs
_bloomParameterScreenTexture = _bloomEffect.Parameters["ScreenTexture"];
```

This shader can be used as a test:
https://github.com/mfigueirido/AdaptableCrtEffect/blob/master/AdaptableCrtEffect/Content/Bloom.fx

#### What version of KNI does the bug occur on:
- KNI 3.13.9001.1
I'm having trouble upgrading to 3.14 so I haven't tried it there yet.

#### What operating system are you using:
- Windows11/Chrome

#### What KNI platform are you using:

- BlazorGL

**Comment by nkast** [comment]
It behaves the same as XNA.
There is nothing to fix here.
