### ISSUE TITLE
Canvas issue in Blazor

### ISSUE THREAD

**Issue by Ved-s** [kniEngine/kni#261]
Canvas reference in GameWindow becomes invalid when page content changes, like when adding blazor elements into it

Package: nkast.Xna.Framework.Blazor 3.8.9102

**Comment by nkast** [comment]
The usage you describe is outside the scope of the Game class which is for self-contained Games.
The Blazor template is used only for compiling the C# into wasm.
In fact, the template has been striped down to only what is required to build a static html page.
It is assumed that the GameWindow correspond to the HTMLWindow/Document, 
and the BackBuffer is 100% of the window.

A solution is to place the BlazorGL in an IFrame, see:
https://kniengine.github.io/XNAGameStudio/wasm/Shape-Rendering

Perhaps we could one day have 'islands' inside an HTML to render into individual canvas elements, 
but I don't see the Game class hosting those. 
Instead, the first prof of concept will probably have a different implementation of GraphicsDeviceManager and it's interfaces,
and be proper Blazor Component.
