### ISSUE TITLE
Touch gestures

### ISSUE THREAD

**Issue by davidhesselbom** [kniEngine/kni#742]
I'm trying to get gestures working, i.e. dragging with a finger a smartphone screen.

Using the default template, the game ends up with a file named `Window.6.0.2.js` that defines a bunch of window events, and using the browser's debugger and "device emulation" mode, I can see the events `window.onmousedown` and `window.onmouseup` are firing. However, `window.ontouchstart` never fires...

So, I added this in `index.html`:

```js
        window.addEventListener('touchstart', function (e) {
            console.log("event start")
            var touchobj = e.changedTouches[0];
            startx = parseInt(touchobj.clientX);
            starty = parseInt(touchobj.clientY);
            console.log("event start done", startx, starty)
        }, false);
```

and then I get the expected output in the console when clicking around in "device emulation" mode, but `window.ontouchstart` still isn't firing.

Also, I added this to the `Update` method of the game:

```csharp
            var state = Mouse.GetState();
            Console.WriteLine($"{new Point(state.X, state.Y)} {state.LeftButton}");
```

and when using the browser's "device emulation" mode, the button is always "Released", never "Pressed", despite the fact that, as mentioned earlier, the events `window.onmousedown` and `window.onmouseup` in `Window.6.0.2.js` are both firing.

Maybe I'm missing something obvious?

**Comment by nkast** [comment]
Touch is problematic.
Chrome fix and break it on every version,
If you google it you will that that it's a problem for over a decade now. What the device emulator does on the desktop is complitly irrelevant.

If i remember correctly the mobile version of firefox worked as
expected.

**Comment by andrewandrepowell** [comment]
If it's not too late to give a response, but I recently figured out adding the event listener to the document object, i.e. `winder.document.addEventListener(...)` worked for me.

**Comment by nkast** [comment]
Interesting.

Did you modify events in the 'Window.8.0.0.js' 

https://github.com/nkast/Wasm/blob/main/Wasm.Dom/wwwroot/js/Window.8.0.0.js#L73-L106

**Comment by nkast** [comment]
I updated the Wasm samples to use the touch events from Window, and added the following code in Boids. 
The events look to be working there.

`
            var cc = dc.CanvasContext;
            {
                // draw fps
                cc.Save();
                cc.Scale(2,2);
                cc.FillStyle = "#603090";
                cc.Font = $"24px bold Verdana";
                cc.TextAlign = TextAlign.Left;
                cc.TextBaseline = TextBaseline.Middle;

                cc.FillText("currMouseState: " + currMouseState.Position.ToString(), 0, 40);

                cc.FillText("currTouchState: " + currTouchState.Position.ToString() + ", is pressed " + currTouchState.IsPressed, 0, 80);
                cc.FillText("currTouchState.isPressed " + currTouchState.IsPressed, 0, 110);

                cc.Restore();
            }
`

Then tested the Primitives3D sample on the phone, and indeed, the touch are not registering.
https://kniengine.github.io/XNAGameStudio/wasm/Primitives3D/index.html

**Comment by nkast** [comment]
fixed by [make nkJSObject handlers 1-Based](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwjl0re6npqHAxV7SPEDHbySBrgQFnoECBUQAw&url=https%3A%2F%2Fdev.to%2F3bdelrahman%2Fexploring-1-based-indexing-in-programming-languages-169k&usg=AOvVaw24y8uHIWOqAc_k8v1u20Me&opi=89978449)

The issue was that Window JS object was getting uid 0.
The TouchPanel was checking WindowHandle for IntPtr.Zero and incorrectly assumed that the WindowHandle was not set.

**Comment by davidhesselbom** [comment]
> fixed by [make nkJSObject handlers 1-Based](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwjl0re6npqHAxV7SPEDHbySBrgQFnoECBUQAw&url=https%3A%2F%2Fdev.to%2F3bdelrahman%2Fexploring-1-based-indexing-in-programming-languages-169k&usg=AOvVaw24y8uHIWOqAc_k8v1u20Me&opi=89978449)

Sorry, what was the actual fix? I don't see a related commit...

**Comment by nkast** [comment]
> > fixed by [make nkJSObject handlers 1-Based](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwjl0re6npqHAxV7SPEDHbySBrgQFnoECBUQAw&url=https%3A%2F%2Fdev.to%2F3bdelrahman%2Fexploring-1-based-indexing-in-programming-languages-169k&usg=AOvVaw24y8uHIWOqAc_k8v1u20Me&opi=89978449)
> 
> Sorry, what was the actual fix? I don't see a related commit... Did you change anything in kni, or do I have to change something on my end?

Wrong link, sorry. The fix was in the Wasm bindings library.
The upgrade to Wasm 8.0.1 should fix the TouchPanel.

**Comment by davidhesselbom** [comment]
Sorry, with `Mouse.GetState()`, I still only get the position when using touch, no mouse button is ever down. And `TouchPanel.GetState()` is always empty, and `TouchPanel.IsGestureAvailable` is always false. What am I missing? Is `TouchPanel` supposed to work, or no?

**Comment by nkast** [comment]
Yes, it's supposed to work now.

**Comment by nkast** [comment]
@davidhesselbom 
Just making sure here that everything is in place...
Did you update the js files to 8.0.1?
https://github.com/kniEngine/kni/blob/main/Documentation/articles/migrate_3_12.md#migrating-blazorgl-projects

Also try to clean the browser cache.

Can you explain what's wrong with MouseState?
Normally you shouldn't get mouse events on a touch/mob0ile platform.

**Comment by davidhesselbom** [comment]
Hi, sorry, looks like you were right. It's working now, maybe clearing the cache did the trick.

Both touch (the number of fingers on the screen), mouse position and mouse buttons are reported correctly. Mouse scrolls don't seem to register though, and neither are touch *gestures*.

I guess I should do a bit of digging myself, but, as a starting point, could you please direct me to wherever it is that input (mouse, touch, etc) is passed from JavaScript into C# itself? If I wanted to fake touch gestures and make trick `TouchPanel` into thinking a gesture was made, where's the API for doing that from JavaScript?

**Comment by nkast** [comment]
@davidhesselbom 

The JavaScript code is in the Wasm library, 
Specifically, here is where it passes the Mouse events 
https://github.com/nkast/Wasm/blob/a1aa9496d16c27bbd092a5513c494f11818536f6/Wasm.Dom/wwwroot/js/Window.8.0.1.js#L46-L65
And here are the Touch events
https://github.com/nkast/Wasm/blob/a1aa9496d16c27bbd092a5513c494f11818536f6/Wasm.Dom/wwwroot/js/Window.8.0.1.js#L77-L113

There is no platform-specific code for gestures, Gestures are detected from the touch events. 
That means that you can cross check on other platforms, like UWP or Android, and they should work the same.
Here is where gestures are handled:
https://github.com/kniEngine/kni/blob/main/src/Xna.Framework.Input/Input/Touch/TouchPanelStrategy.Legacy.cs#L281

The code is not pretty. Only the simpler gestures are currently implemented. We probably have to rewrite everything with a proper state machine.

**Comment by davidhesselbom** [comment]
Awesome, thanks for the links!

**Comment by davidhesselbom** [comment]
Sorry to bother you again, but I'm still missing something. 

The js code you linked to calls JsWindowOnTouchStart, defined here:

https://github.com/nkast/Wasm/blob/a1aa9496d16c27bbd092a5513c494f11818536f6/Wasm.Dom/Dom/Window.cs#L184-L190

That function, in turn, calls the handler `wnd.OnTouchStart`. Where is this handler defined, and where is wnd.OnTouchStart assigned? I've searched across your repos but found nothing...

**Comment by nkast** [comment]
It calls the C# method JsWindowOnTouchStart in Dom/Window.cs
which fires the Window.OnTouchStart.

We capture those events in the BlazorGL backend in BlazorGameWindow.cs
https://github.com/kniEngine/kni/blob/a22df9536ad7a6028d5e5929bd795e2658915755/Platforms/Platform/Blazor/BlazorGameWindow.cs#L131-L149
